networks:
  monitoring:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    init: true
    user: postgres
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - monitoring

  atlas:
    container_name: atlas
    image: mongodb/mongodb-atlas-local:latest   
    env_file:
      - path: .env
        required: true
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${ATLAS_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${ATLAS_INITDB_ROOT_PASSWORD}    
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - atlas-db-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - monitoring

  hyperdrive-identity-service:
    container_name: hyperdrive-identity-service
    image: ${DOCKER_REGISTRY-}hyperdrive-identity-service    
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: Hyperdrive.Identity.Service/Hyperdrive.Identity.Service/Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: 8070
      ASPNETCORE_HTTPS_PORTS: 8071
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      ConnectionStrings__DefaultConnection: ${PG_CONNECTION}
      Jwt__JwtAudience: ${JWT_AUDIENCE}    
      Jwt__JwtAuthority: ${JWT_AUTHORITY}
      Jwt__JwtIssuer: ${JWT_ISSUER}
      Jwt__JwtKey: ${JWT_KEY}
    ports:
      - "8070:8070"
      - "8071:8071"
    networks:
      - monitoring
    depends_on:
      - postgres

  hyperdrive-storage-service:
    container_name: hyperdrive-storage-service
    image: ${DOCKER_REGISTRY-}hyperdrive-storage-service    
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: Hyperdrive.Storage.Service/Hyperdrive.Storage.storage/Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      ConnectionStrings__DefaultConnection: ${PG_CONNECTION}
      Jwt__JwtAudience: ${JWT_AUDIENCE}    
      Jwt__JwtAuthority: ${JWT_AUTHORITY}
      Jwt__JwtIssuer: ${JWT_ISSUER}
      Jwt__JwtKey: ${JWT_KEY}
    ports:
      - "8080:8080
      - "8081:8081"
    networks:
      - monitoring
    depends_on:
      - postgres

  hyperdrive-intelligence-service:
    container_name: hyperdrive-intelligence-service
    image: ${DOCKER_REGISTRY-}hyperdrive-intelligence-service  
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: Hyperdrive.Intelligence.Service/Hyperdrive.Intelligence.Service/Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: 8090
      ASPNETCORE_HTTPS_PORTS: 8091
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      ConnectionStrings__DefaultConnection: ${ATLAS_CONNECTION}      
    ports:
      - "8090:8090
      - "8091:8091"
    networks:
      - monitoring
    depends_on:
      - atlas

volumes:
  pg-db-data:
  atlas-db-data:
