networks:
  monitoring:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    init: true
    user: postgres
    env_file:
      - path: .env
        required: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - pg-db-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    networks:
      - monitoring

  atlas:
    container_name: atlas
    image: mongodb/mongodb-atlas-local:latest   
    env_file:
      - path: .env
        required: true
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${ATLAS_INITDB_ROOT_USERNAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${ATLAS_INITDB_ROOT_PASSWORD}    
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - atlas-db-data:/data/db
    ports:
      - "${ATLAS_PORT}:${ATLAS_PORT}"
    networks:
      - monitoring

  hyperdrive-main-service:
    container_name: hyperdrive-main-service
    image: ${DOCKER_REGISTRY-}hyperdrive-main-service    
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: Hyperdrive.Main.Service/Hyperdrive.Main.Service/Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
      ASPNETCORE_HTTPS_PORTS: ${ASPNETCORE_HTTPS_PORTS}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      ConnectionStrings__DefaultConnection: ${PG_CONNECTION}
      Jwt__JwtAudience: ${JWT_AUDIENCE}    
      Jwt__JwtAuthority: ${JWT_AUTHORITY}
      Jwt__JwtIssuer: ${JWT_ISSUER}
      Jwt__JwtKey: ${JWT_KEY}
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"
      - "${ASPNETCORE_HTTPS_PORTS}:${ASPNETCORE_HTTPS_PORTS}"
    networks:
      - monitoring
    depends_on:
      - postgres

  hyperdrive-ai-service:
    container_name: hyperdrive-ai-service
    image: ${DOCKER_REGISTRY-}hyperdrive-ai-service  
    restart: unless-stopped
    init: true
    build:
      context: .
      dockerfile: Hyperdrive.Ai.Service/Hyperdrive.Ai.Service/Dockerfile
    env_file:
      - path: .env
        required: true
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_HTTP_PORTS: ${ASPNETCORE_HTTP_PORTS}
      ASPNETCORE_HTTPS_PORTS: ${ASPNETCORE_HTTPS_PORTS}
      OTEL_EXPORTER_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}
      ConnectionStrings__DefaultConnection: ${ATLAS_CONNECTION}      
    ports:
      - "${ASPNETCORE_HTTP_PORTS}:${ASPNETCORE_HTTP_PORTS}"
      - "${ASPNETCORE_HTTPS_PORTS}:${ASPNETCORE_HTTPS_PORTS}"
    networks:
      - monitoring
    depends_on:
      - atlas

volumes:
  pg-db-data:
  atlas-db-data:
